# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

import numpy as np
from fractions import Fraction
from sympy import *
from Gauss import *
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TareaAlgebra(object):
    matrizEnInterfaz = []
    matrizActiva = []
    matrizReal = []
    matrizSYMPY = []
    base1 = []
    base2 = []
    base3 = []
    base4 = []
    base5 = []
    bases = []

    filas = 5
    columnas = 5

    def setupUi(self, TareaAlgebra):
        TareaAlgebra.setObjectName("TareaAlgebra")
        TareaAlgebra.resize(919, 519)
        TareaAlgebra.setWindowOpacity(1.0)
        TareaAlgebra.setStyleSheet("background-color: rgb(172, 172, 172)")
        self.centralwidget = QtWidgets.QWidget(TareaAlgebra)
        self.centralwidget.setObjectName("centralwidget")
        self.FilasGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.FilasGroupBox.setGeometry(QtCore.QRect(30, 10, 181, 51))
        self.FilasGroupBox.setObjectName("FilasGroupBox")
        self.filas2 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas2.setGeometry(QtCore.QRect(10, 20, 31, 17))
        self.filas2.setChecked(False)
        self.filas2.setObjectName("filas2")
        self.filas3 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas3.setGeometry(QtCore.QRect(50, 20, 31, 17))
        self.filas3.setObjectName("filas3")
        self.filas4 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas4.setGeometry(QtCore.QRect(90, 20, 31, 17))
        self.filas4.setObjectName("filas4")
        self.filas5 = QtWidgets.QRadioButton(self.FilasGroupBox)
        self.filas5.setGeometry(QtCore.QRect(130, 20, 41, 17))
        self.filas5.setChecked(True)
        self.filas5.setObjectName("filas5")
        self.ColumnasGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ColumnasGroupBox.setGeometry(QtCore.QRect(30, 90, 181, 51))
        self.ColumnasGroupBox.setObjectName("ColumnasGroupBox")
        self.col2 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col2.setGeometry(QtCore.QRect(10, 20, 31, 17))
        self.col2.setChecked(False)
        self.col2.setObjectName("col2")
        self.col3 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col3.setGeometry(QtCore.QRect(50, 20, 31, 17))
        self.col3.setObjectName("col3")
        self.col4 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col4.setGeometry(QtCore.QRect(90, 20, 31, 17))
        self.col4.setObjectName("col4")
        self.col5 = QtWidgets.QRadioButton(self.ColumnasGroupBox)
        self.col5.setGeometry(QtCore.QRect(130, 20, 41, 17))
        self.col5.setChecked(True)
        self.col5.setObjectName("col5")
        self.nuevaMatrizButt = QtWidgets.QPushButton(self.centralwidget)
        self.nuevaMatrizButt.setGeometry(QtCore.QRect(60, 400, 141, 23))
        self.nuevaMatrizButt.setObjectName("nuevaMatrizButt")
        self.sResutadosButt = QtWidgets.QPushButton(self.centralwidget)
        self.sResutadosButt.setGeometry(QtCore.QRect(60, 440, 141, 23))
        self.sResutadosButt.setObjectName("sResutadosButt")
        self.FIL1COL1 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL1COL1.setGeometry(QtCore.QRect(260, 10, 51, 91))
        self.FIL1COL1.setTitle("")
        self.FIL1COL1.setObjectName("FIL1COL1")
        self.DEMF1C1 = QtWidgets.QLineEdit(self.FIL1COL1)
        self.DEMF1C1.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF1C1.setObjectName("DEMF1C1")
        self.line = QtWidgets.QFrame(self.FIL1COL1)
        self.line.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.NUMF1C1 = QtWidgets.QLineEdit(self.FIL1COL1)
        self.NUMF1C1.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF1C1.setObjectName("NUMF1C1")
        self.FIL1COL2 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL1COL2.setGeometry(QtCore.QRect(390, 10, 51, 91))
        self.FIL1COL2.setTitle("")
        self.FIL1COL2.setObjectName("FIL1COL2")
        self.DEMF1C2 = QtWidgets.QLineEdit(self.FIL1COL2)
        self.DEMF1C2.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF1C2.setObjectName("DEMF1C2")
        self.line_12 = QtWidgets.QFrame(self.FIL1COL2)
        self.line_12.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.NUMF1C2 = QtWidgets.QLineEdit(self.FIL1COL2)
        self.NUMF1C2.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF1C2.setObjectName("NUMF1C2")
        self.FIL1COL3 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL1COL3.setGeometry(QtCore.QRect(520, 10, 51, 91))
        self.FIL1COL3.setTitle("")
        self.FIL1COL3.setObjectName("FIL1COL3")
        self.DEMF1C3 = QtWidgets.QLineEdit(self.FIL1COL3)
        self.DEMF1C3.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF1C3.setObjectName("DEMF1C3")
        self.line_13 = QtWidgets.QFrame(self.FIL1COL3)
        self.line_13.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.NUMF1C3 = QtWidgets.QLineEdit(self.FIL1COL3)
        self.NUMF1C3.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF1C3.setObjectName("NUMF1C3")
        self.FIL1COL4 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL1COL4.setGeometry(QtCore.QRect(650, 10, 51, 91))
        self.FIL1COL4.setTitle("")
        self.FIL1COL4.setObjectName("FIL1COL4")
        self.DEMF1C4 = QtWidgets.QLineEdit(self.FIL1COL4)
        self.DEMF1C4.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF1C4.setObjectName("DEMF1C4")
        self.line_14 = QtWidgets.QFrame(self.FIL1COL4)
        self.line_14.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.NUMF1C4 = QtWidgets.QLineEdit(self.FIL1COL4)
        self.NUMF1C4.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF1C4.setObjectName("NUMF1C4")
        self.FIL1COL5 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL1COL5.setGeometry(QtCore.QRect(780, 10, 51, 91))
        self.FIL1COL5.setTitle("")
        self.FIL1COL5.setObjectName("FIL1COL5")
        self.DEMF1C5 = QtWidgets.QLineEdit(self.FIL1COL5)
        self.DEMF1C5.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF1C5.setObjectName("DEMF1C5")
        self.line_15 = QtWidgets.QFrame(self.FIL1COL5)
        self.line_15.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.NUMF1C5 = QtWidgets.QLineEdit(self.FIL1COL5)
        self.NUMF1C5.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF1C5.setObjectName("NUMF1C5")
        self.FIL2COL1 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL2COL1.setGeometry(QtCore.QRect(260, 110, 51, 91))
        self.FIL2COL1.setTitle("")
        self.FIL2COL1.setObjectName("FIL2COL1")
        self.DEMF2C1 = QtWidgets.QLineEdit(self.FIL2COL1)
        self.DEMF2C1.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF2C1.setObjectName("DEMF2C1")
        self.line_16 = QtWidgets.QFrame(self.FIL2COL1)
        self.line_16.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.NUMF2C1 = QtWidgets.QLineEdit(self.FIL2COL1)
        self.NUMF2C1.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF2C1.setObjectName("NUMF2C1")
        self.FIL2COL2 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL2COL2.setGeometry(QtCore.QRect(390, 110, 51, 91))
        self.FIL2COL2.setTitle("")
        self.FIL2COL2.setObjectName("FIL2COL2")
        self.DEMF2C2 = QtWidgets.QLineEdit(self.FIL2COL2)
        self.DEMF2C2.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF2C2.setObjectName("DEMF2C2")
        self.line_17 = QtWidgets.QFrame(self.FIL2COL2)
        self.line_17.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.NUMF2C2 = QtWidgets.QLineEdit(self.FIL2COL2)
        self.NUMF2C2.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF2C2.setObjectName("NUMF2C2")
        self.FIL2COL3 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL2COL3.setGeometry(QtCore.QRect(520, 110, 51, 91))
        self.FIL2COL3.setTitle("")
        self.FIL2COL3.setObjectName("FIL2COL3")
        self.DEMF2C3 = QtWidgets.QLineEdit(self.FIL2COL3)
        self.DEMF2C3.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF2C3.setObjectName("DEMF2C3")
        self.line_18 = QtWidgets.QFrame(self.FIL2COL3)
        self.line_18.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.NUMF2C3 = QtWidgets.QLineEdit(self.FIL2COL3)
        self.NUMF2C3.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF2C3.setObjectName("NUMF2C3")
        self.FIL2COL4 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL2COL4.setGeometry(QtCore.QRect(650, 110, 51, 91))
        self.FIL2COL4.setTitle("")
        self.FIL2COL4.setObjectName("FIL2COL4")
        self.DEMF2C4 = QtWidgets.QLineEdit(self.FIL2COL4)
        self.DEMF2C4.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF2C4.setObjectName("DEMF2C4")
        self.line_19 = QtWidgets.QFrame(self.FIL2COL4)
        self.line_19.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.NUMF2C4 = QtWidgets.QLineEdit(self.FIL2COL4)
        self.NUMF2C4.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF2C4.setObjectName("NUMF2C4")
        self.FIL2COL5 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL2COL5.setGeometry(QtCore.QRect(780, 110, 51, 91))
        self.FIL2COL5.setTitle("")
        self.FIL2COL5.setObjectName("FIL2COL5")
        self.DEMF2C5 = QtWidgets.QLineEdit(self.FIL2COL5)
        self.DEMF2C5.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF2C5.setObjectName("DEMF2C5")
        self.line_20 = QtWidgets.QFrame(self.FIL2COL5)
        self.line_20.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.NUMF2C5 = QtWidgets.QLineEdit(self.FIL2COL5)
        self.NUMF2C5.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF2C5.setObjectName("NUMF2C5")
        self.FIL3COL1 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL3COL1.setGeometry(QtCore.QRect(260, 210, 51, 91))
        self.FIL3COL1.setTitle("")
        self.FIL3COL1.setObjectName("FIL3COL1")
        self.DEMF3C1 = QtWidgets.QLineEdit(self.FIL3COL1)
        self.DEMF3C1.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF3C1.setObjectName("DEMF3C1")
        self.line_21 = QtWidgets.QFrame(self.FIL3COL1)
        self.line_21.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.NUMF3C1 = QtWidgets.QLineEdit(self.FIL3COL1)
        self.NUMF3C1.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF3C1.setObjectName("NUMF3C1")
        self.FIL3COL2 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL3COL2.setGeometry(QtCore.QRect(390, 210, 51, 91))
        self.FIL3COL2.setTitle("")
        self.FIL3COL2.setObjectName("FIL3COL2")
        self.DEMF3C2 = QtWidgets.QLineEdit(self.FIL3COL2)
        self.DEMF3C2.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF3C2.setObjectName("DEMF3C2")
        self.line_22 = QtWidgets.QFrame(self.FIL3COL2)
        self.line_22.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.NUMF3C2 = QtWidgets.QLineEdit(self.FIL3COL2)
        self.NUMF3C2.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF3C2.setObjectName("NUMF3C2")
        self.FIL3COL3 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL3COL3.setGeometry(QtCore.QRect(520, 210, 51, 91))
        self.FIL3COL3.setTitle("")
        self.FIL3COL3.setObjectName("FIL3COL3")
        self.DEMF3C3 = QtWidgets.QLineEdit(self.FIL3COL3)
        self.DEMF3C3.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF3C3.setObjectName("DEMF3C3")
        self.line_23 = QtWidgets.QFrame(self.FIL3COL3)
        self.line_23.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.NUMF3C3 = QtWidgets.QLineEdit(self.FIL3COL3)
        self.NUMF3C3.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF3C3.setObjectName("NUMF3C3")
        self.FIL3COL4 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL3COL4.setGeometry(QtCore.QRect(650, 210, 51, 91))
        self.FIL3COL4.setTitle("")
        self.FIL3COL4.setObjectName("FIL3COL4")
        self.DEMF3C4 = QtWidgets.QLineEdit(self.FIL3COL4)
        self.DEMF3C4.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF3C4.setObjectName("DEMF3C4")
        self.line_24 = QtWidgets.QFrame(self.FIL3COL4)
        self.line_24.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.NUMF3C4 = QtWidgets.QLineEdit(self.FIL3COL4)
        self.NUMF3C4.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF3C4.setObjectName("NUMF3C4")
        self.FIL3COL5 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL3COL5.setGeometry(QtCore.QRect(780, 210, 51, 91))
        self.FIL3COL5.setTitle("")
        self.FIL3COL5.setObjectName("FIL3COL5")
        self.DEMF3C5 = QtWidgets.QLineEdit(self.FIL3COL5)
        self.DEMF3C5.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF3C5.setObjectName("DEMF3C5")
        self.line_25 = QtWidgets.QFrame(self.FIL3COL5)
        self.line_25.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_25.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.NUMF3C5 = QtWidgets.QLineEdit(self.FIL3COL5)
        self.NUMF3C5.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF3C5.setObjectName("NUMF3C5")
        self.FIL4COL1 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL4COL1.setGeometry(QtCore.QRect(260, 310, 51, 91))
        self.FIL4COL1.setTitle("")
        self.FIL4COL1.setObjectName("FIL4COL1")
        self.DEMF4C1 = QtWidgets.QLineEdit(self.FIL4COL1)
        self.DEMF4C1.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF4C1.setObjectName("DEMF4C1")
        self.line_26 = QtWidgets.QFrame(self.FIL4COL1)
        self.line_26.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.NUMF4C1 = QtWidgets.QLineEdit(self.FIL4COL1)
        self.NUMF4C1.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF4C1.setObjectName("NUMF4C1")
        self.FIL4COL2 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL4COL2.setGeometry(QtCore.QRect(390, 310, 51, 91))
        self.FIL4COL2.setTitle("")
        self.FIL4COL2.setObjectName("FIL4COL2")
        self.DEMF4C2 = QtWidgets.QLineEdit(self.FIL4COL2)
        self.DEMF4C2.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF4C2.setObjectName("DEMF4C2")
        self.line_27 = QtWidgets.QFrame(self.FIL4COL2)
        self.line_27.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.NUMF4C2 = QtWidgets.QLineEdit(self.FIL4COL2)
        self.NUMF4C2.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF4C2.setObjectName("NUMF4C2")
        self.FIL4COL3 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL4COL3.setGeometry(QtCore.QRect(520, 310, 51, 91))
        self.FIL4COL3.setTitle("")
        self.FIL4COL3.setObjectName("FIL4COL3")
        self.DEMF4C3 = QtWidgets.QLineEdit(self.FIL4COL3)
        self.DEMF4C3.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF4C3.setObjectName("DEMF4C3")
        self.line_28 = QtWidgets.QFrame(self.FIL4COL3)
        self.line_28.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.NUMF4C3 = QtWidgets.QLineEdit(self.FIL4COL3)
        self.NUMF4C3.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF4C3.setObjectName("NUMF4C3")
        self.FIL4COL4 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL4COL4.setGeometry(QtCore.QRect(650, 310, 51, 91))
        self.FIL4COL4.setTitle("")
        self.FIL4COL4.setObjectName("FIL4COL4")
        self.DEMF4C4 = QtWidgets.QLineEdit(self.FIL4COL4)
        self.DEMF4C4.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF4C4.setObjectName("DEMF4C4")
        self.line_29 = QtWidgets.QFrame(self.FIL4COL4)
        self.line_29.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_29.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.NUMF4C4 = QtWidgets.QLineEdit(self.FIL4COL4)
        self.NUMF4C4.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF4C4.setObjectName("NUMF4C4")
        self.FIL4COL5 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL4COL5.setGeometry(QtCore.QRect(780, 310, 51, 91))
        self.FIL4COL5.setTitle("")
        self.FIL4COL5.setObjectName("FIL4COL5")
        self.DEMF4C5 = QtWidgets.QLineEdit(self.FIL4COL5)
        self.DEMF4C5.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF4C5.setObjectName("DEMF4C5")
        self.line_30 = QtWidgets.QFrame(self.FIL4COL5)
        self.line_30.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.NUMF4C5 = QtWidgets.QLineEdit(self.FIL4COL5)
        self.NUMF4C5.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF4C5.setObjectName("NUMF4C5")
        self.FIL5COL1 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL5COL1.setGeometry(QtCore.QRect(260, 410, 51, 91))
        self.FIL5COL1.setTitle("")
        self.FIL5COL1.setObjectName("FIL5COL1")
        self.DEMF5C1 = QtWidgets.QLineEdit(self.FIL5COL1)
        self.DEMF5C1.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF5C1.setObjectName("DEMF5C1")
        self.line_31 = QtWidgets.QFrame(self.FIL5COL1)
        self.line_31.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.NUMF5C1 = QtWidgets.QLineEdit(self.FIL5COL1)
        self.NUMF5C1.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF5C1.setObjectName("NUMF5C1")
        self.FIL5COL2 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL5COL2.setGeometry(QtCore.QRect(390, 410, 51, 91))
        self.FIL5COL2.setTitle("")
        self.FIL5COL2.setObjectName("FIL5COL2")
        self.DEMF5C2 = QtWidgets.QLineEdit(self.FIL5COL2)
        self.DEMF5C2.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF5C2.setObjectName("DEMF5C2")
        self.line_32 = QtWidgets.QFrame(self.FIL5COL2)
        self.line_32.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.NUMF5C2 = QtWidgets.QLineEdit(self.FIL5COL2)
        self.NUMF5C2.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF5C2.setObjectName("NUMF5C2")
        self.FIL5COL3 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL5COL3.setGeometry(QtCore.QRect(520, 410, 51, 91))
        self.FIL5COL3.setTitle("")
        self.FIL5COL3.setObjectName("FIL5COL3")
        self.DEMF5C3 = QtWidgets.QLineEdit(self.FIL5COL3)
        self.DEMF5C3.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF5C3.setObjectName("DEMF5C3")
        self.line_33 = QtWidgets.QFrame(self.FIL5COL3)
        self.line_33.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.NUMF5C3 = QtWidgets.QLineEdit(self.FIL5COL3)
        self.NUMF5C3.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF5C3.setObjectName("NUMF5C3")
        self.FIL5COL4 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL5COL4.setGeometry(QtCore.QRect(650, 410, 51, 91))
        self.FIL5COL4.setTitle("")
        self.FIL5COL4.setObjectName("FIL5COL4")
        self.DEMF5C4 = QtWidgets.QLineEdit(self.FIL5COL4)
        self.DEMF5C4.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF5C4.setObjectName("DEMF5C4")
        self.line_34 = QtWidgets.QFrame(self.FIL5COL4)
        self.line_34.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.NUMF5C4 = QtWidgets.QLineEdit(self.FIL5COL4)
        self.NUMF5C4.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF5C4.setObjectName("NUMF5C4")
        self.FIL5COL5 = QtWidgets.QGroupBox(self.centralwidget)
        self.FIL5COL5.setEnabled(True)
        self.FIL5COL5.setGeometry(QtCore.QRect(780, 410, 51, 91))
        self.FIL5COL5.setTitle("")
        self.FIL5COL5.setObjectName("FIL5COL5")
        self.DEMF5C5 = QtWidgets.QLineEdit(self.FIL5COL5)
        self.DEMF5C5.setGeometry(QtCore.QRect(10, 60, 31, 20))
        self.DEMF5C5.setObjectName("DEMF5C5")
        self.line_35 = QtWidgets.QFrame(self.FIL5COL5)
        self.line_35.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.NUMF5C5 = QtWidgets.QLineEdit(self.FIL5COL5)
        self.NUMF5C5.setGeometry(QtCore.QRect(10, 10, 31, 20))
        self.NUMF5C5.setObjectName("NUMF5C5")
        self.OperacionesElementalesGrupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.OperacionesElementalesGrupBox.setGeometry(QtCore.QRect(10, 160, 231, 221))
        self.OperacionesElementalesGrupBox.setStyleSheet("")
        self.OperacionesElementalesGrupBox.setObjectName("OperacionesElementalesGrupBox")
        self.labelSolUnic = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.labelSolUnic.setGeometry(QtCore.QRect(20, 30, 181, 21))
        self.labelSolUnic.setText("")
        self.labelSolUnic.setObjectName("labelSolUnic")
        self.sol11 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol11.setGeometry(QtCore.QRect(20, 65, 31, 21))
        self.sol11.setAutoFillBackground(False)
        self.sol11.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.sol11.setText("")
        self.sol11.setObjectName("sol11")
        self.sol21 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol21.setGeometry(QtCore.QRect(20, 96, 31, 20))
        self.sol21.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.sol21.setText("")
        self.sol21.setObjectName("sol21")
        self.sol31 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol31.setGeometry(QtCore.QRect(20, 126, 31, 20))
        self.sol31.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.sol31.setText("")
        self.sol31.setObjectName("sol31")
        self.sol41 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol41.setGeometry(QtCore.QRect(20, 155, 31, 21))
        self.sol41.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.sol41.setText("")
        self.sol41.setObjectName("sol41")
        self.sol51 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol51.setGeometry(QtCore.QRect(20, 186, 31, 20))
        self.sol51.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.sol51.setText("")
        self.sol51.setObjectName("sol51")
        self.sol12 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol12.setGeometry(QtCore.QRect(60, 66, 31, 20))
        self.sol12.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.sol12.setText("")
        self.sol12.setObjectName("sol12")
        self.sol22 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol22.setGeometry(QtCore.QRect(60, 95, 31, 21))
        self.sol22.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.sol22.setText("")
        self.sol22.setObjectName("sol22")
        self.sol32 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol32.setGeometry(QtCore.QRect(60, 126, 31, 20))
        self.sol32.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.sol32.setText("")
        self.sol32.setObjectName("sol32")
        self.sol42 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol42.setGeometry(QtCore.QRect(60, 156, 31, 20))
        self.sol42.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.sol42.setText("")
        self.sol42.setObjectName("sol42")
        self.sol52 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol52.setGeometry(QtCore.QRect(60, 186, 31, 20))
        self.sol52.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.sol52.setText("")
        self.sol52.setObjectName("sol52")
        self.sol13 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol13.setGeometry(QtCore.QRect(100, 66, 31, 20))
        self.sol13.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.sol13.setText("")
        self.sol13.setObjectName("sol13")
        self.sol23 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol23.setGeometry(QtCore.QRect(100, 95, 31, 21))
        self.sol23.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.sol23.setText("")
        self.sol23.setObjectName("sol23")
        self.sol33 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol33.setGeometry(QtCore.QRect(100, 126, 31, 20))
        self.sol33.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.sol33.setText("")
        self.sol33.setObjectName("sol33")
        self.sol43 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol43.setGeometry(QtCore.QRect(100, 155, 31, 21))
        self.sol43.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.sol43.setText("")
        self.sol43.setObjectName("sol43")
        self.sol53 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol53.setGeometry(QtCore.QRect(100, 185, 31, 21))
        self.sol53.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.sol53.setText("")
        self.sol53.setObjectName("sol53")
        self.sol14 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol14.setGeometry(QtCore.QRect(140, 66, 31, 20))
        self.sol14.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.sol14.setText("")
        self.sol14.setObjectName("sol14")
        self.sol24 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol24.setGeometry(QtCore.QRect(140, 96, 31, 20))
        self.sol24.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.sol24.setText("")
        self.sol24.setObjectName("sol24")
        self.sol34 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol34.setGeometry(QtCore.QRect(140, 125, 31, 21))
        self.sol34.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.sol34.setText("")
        self.sol34.setObjectName("sol34")
        self.sol44 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol44.setGeometry(QtCore.QRect(140, 156, 31, 20))
        self.sol44.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.sol44.setText("")
        self.sol44.setObjectName("sol44")
        self.sol54 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol54.setGeometry(QtCore.QRect(140, 186, 31, 20))
        self.sol54.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.sol54.setText("")
        self.sol54.setObjectName("sol54")
        self.sol15 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol15.setGeometry(QtCore.QRect(180, 66, 31, 20))
        self.sol15.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.sol15.setText("")
        self.sol15.setObjectName("sol15")
        self.sol25 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol25.setGeometry(QtCore.QRect(180, 95, 31, 21))
        self.sol25.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.sol25.setText("")
        self.sol25.setObjectName("sol25")
        self.sol35 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol35.setGeometry(QtCore.QRect(180, 126, 31, 20))
        self.sol35.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.sol35.setText("")
        self.sol35.setObjectName("sol35")
        self.sol45 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol45.setGeometry(QtCore.QRect(180, 156, 31, 20))
        self.sol45.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.sol45.setText("")
        self.sol45.setObjectName("sol45")
        self.sol55 = QtWidgets.QLabel(self.OperacionesElementalesGrupBox)
        self.sol55.setGeometry(QtCore.QRect(180, 185, 31, 21))
        self.sol55.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.sol55.setText("")
        self.sol55.setObjectName("sol55")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(330, 20, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(460, 20, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(590, 20, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(720, 20, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(850, 20, 51, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(850, 120, 51, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(840, 220, 51, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(850, 320, 51, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(850, 420, 51, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(720, 120, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(720, 220, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(720, 320, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(720, 420, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(590, 120, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(590, 220, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(590, 310, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(590, 420, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(460, 120, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(460, 220, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(460, 320, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(460, 420, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(330, 120, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(330, 220, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(330, 320, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(330, 410, 41, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(True)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.ErrorMessage = QtWidgets.QLabel(self.centralwidget)
        self.ErrorMessage.setGeometry(QtCore.QRect(80, 480, 91, 31))
        self.ErrorMessage.setText("")
        self.ErrorMessage.setObjectName("ErrorMessage")
        TareaAlgebra.setCentralWidget(self.centralwidget)
        self.sResutadosButt.setEnabled(False)
        self.retranslateUi(TareaAlgebra)
        QtCore.QMetaObject.connectSlotsByName(TareaAlgebra)
        self.base1 = [self.sol11, self.sol21, self.sol31, self.sol41, self.sol51]
        self.base2 = [self.sol12, self.sol22, self.sol32, self.sol42, self.sol52]
        self.base3 = [self.sol13, self.sol23, self.sol33, self.sol43, self.sol53]
        self.base4 = [self.sol14, self.sol24, self.sol34, self.sol44, self.sol54]
        self.base5 = [self.sol15, self.sol25, self.sol35, self.sol45, self.sol55]
        self.bases = [self.base1, self.base2, self.base3, self.base4, self.base5]
        self.home()

    def retranslateUi(self, TareaAlgebra):
        _translate = QtCore.QCoreApplication.translate
        TareaAlgebra.setWindowTitle(_translate("TareaAlgebra", "MainWindow"))
        self.FilasGroupBox.setTitle(_translate("TareaAlgebra", "Ecuaciones"))
        self.filas2.setText(_translate("TareaAlgebra", "2"))
        self.filas3.setText(_translate("TareaAlgebra", "3"))
        self.filas4.setText(_translate("TareaAlgebra", "4"))
        self.filas5.setText(_translate("TareaAlgebra", "5"))
        self.ColumnasGroupBox.setTitle(_translate("TareaAlgebra", "Variables"))
        self.col2.setText(_translate("TareaAlgebra", "2"))
        self.col3.setText(_translate("TareaAlgebra", "3"))
        self.col4.setText(_translate("TareaAlgebra", "4"))
        self.col5.setText(_translate("TareaAlgebra", "5"))
        self.nuevaMatrizButt.setText(_translate("TareaAlgebra", "Resetear"))
        self.sResutadosButt.setText(_translate("TareaAlgebra", "Resolver"))
        self.DEMF1C1.setText(_translate("TareaAlgebra", "1"))
        self.NUMF1C1.setText(_translate("TareaAlgebra", "0"))
        self.DEMF1C2.setText(_translate("TareaAlgebra", "1"))
        self.NUMF1C2.setText(_translate("TareaAlgebra", "0"))
        self.DEMF1C3.setText(_translate("TareaAlgebra", "1"))
        self.NUMF1C3.setText(_translate("TareaAlgebra", "0"))
        self.DEMF1C4.setText(_translate("TareaAlgebra", "1"))
        self.NUMF1C4.setText(_translate("TareaAlgebra", "0"))
        self.DEMF1C5.setText(_translate("TareaAlgebra", "1"))
        self.NUMF1C5.setText(_translate("TareaAlgebra", "0"))
        self.DEMF2C1.setText(_translate("TareaAlgebra", "1"))
        self.NUMF2C1.setText(_translate("TareaAlgebra", "0"))
        self.DEMF2C2.setText(_translate("TareaAlgebra", "1"))
        self.NUMF2C2.setText(_translate("TareaAlgebra", "0"))
        self.DEMF2C3.setText(_translate("TareaAlgebra", "1"))
        self.NUMF2C3.setText(_translate("TareaAlgebra", "0"))
        self.DEMF2C4.setText(_translate("TareaAlgebra", "1"))
        self.NUMF2C4.setText(_translate("TareaAlgebra", "0"))
        self.DEMF2C5.setText(_translate("TareaAlgebra", "1"))
        self.NUMF2C5.setText(_translate("TareaAlgebra", "0"))
        self.DEMF3C1.setText(_translate("TareaAlgebra", "1"))
        self.NUMF3C1.setText(_translate("TareaAlgebra", "0"))
        self.DEMF3C2.setText(_translate("TareaAlgebra", "1"))
        self.NUMF3C2.setText(_translate("TareaAlgebra", "0"))
        self.DEMF3C3.setText(_translate("TareaAlgebra", "1"))
        self.NUMF3C3.setText(_translate("TareaAlgebra", "0"))
        self.DEMF3C4.setText(_translate("TareaAlgebra", "1"))
        self.NUMF3C4.setText(_translate("TareaAlgebra", "0"))
        self.DEMF3C5.setText(_translate("TareaAlgebra", "1"))
        self.NUMF3C5.setText(_translate("TareaAlgebra", "0"))
        self.DEMF4C1.setText(_translate("TareaAlgebra", "1"))
        self.NUMF4C1.setText(_translate("TareaAlgebra", "0"))
        self.DEMF4C2.setText(_translate("TareaAlgebra", "1"))
        self.NUMF4C2.setText(_translate("TareaAlgebra", "0"))
        self.DEMF4C3.setText(_translate("TareaAlgebra", "1"))
        self.NUMF4C3.setText(_translate("TareaAlgebra", "0"))
        self.DEMF4C4.setText(_translate("TareaAlgebra", "1"))
        self.NUMF4C4.setText(_translate("TareaAlgebra", "0"))
        self.DEMF4C5.setText(_translate("TareaAlgebra", "1"))
        self.NUMF4C5.setText(_translate("TareaAlgebra", "0"))
        self.DEMF5C1.setText(_translate("TareaAlgebra", "1"))
        self.NUMF5C1.setText(_translate("TareaAlgebra", "0"))
        self.DEMF5C2.setText(_translate("TareaAlgebra", "1"))
        self.NUMF5C2.setText(_translate("TareaAlgebra", "0"))
        self.DEMF5C3.setText(_translate("TareaAlgebra", "1"))
        self.NUMF5C3.setText(_translate("TareaAlgebra", "0"))
        self.DEMF5C4.setText(_translate("TareaAlgebra", "1"))
        self.NUMF5C4.setText(_translate("TareaAlgebra", "0"))
        self.DEMF5C5.setText(_translate("TareaAlgebra", "1"))
        self.NUMF5C5.setText(_translate("TareaAlgebra", "0"))
        self.OperacionesElementalesGrupBox.setTitle(_translate("TareaAlgebra", "Resultados"))
        self.label_10.setText(_translate("TareaAlgebra", "X1+"))
        self.label_11.setText(_translate("TareaAlgebra", "X2+"))
        self.label_12.setText(_translate("TareaAlgebra", "X3+"))
        self.label_13.setText(_translate("TareaAlgebra", "X4+"))
        self.label_14.setText(_translate("TareaAlgebra", "X5=0"))
        self.label_15.setText(_translate("TareaAlgebra", "X5=0"))
        self.label_16.setText(_translate("TareaAlgebra", "X5=0"))
        self.label_17.setText(_translate("TareaAlgebra", "X5=0"))
        self.label_18.setText(_translate("TareaAlgebra", "X5=0"))
        self.label_19.setText(_translate("TareaAlgebra", "X4+"))
        self.label_20.setText(_translate("TareaAlgebra", "X4+"))
        self.label_21.setText(_translate("TareaAlgebra", "X4+"))
        self.label_22.setText(_translate("TareaAlgebra", "X4+"))
        self.label_23.setText(_translate("TareaAlgebra", "X3+"))
        self.label_24.setText(_translate("TareaAlgebra", "X3+"))
        self.label_25.setText(_translate("TareaAlgebra", "X3+"))
        self.label_26.setText(_translate("TareaAlgebra", "X3+"))
        self.label_27.setText(_translate("TareaAlgebra", "X2+"))
        self.label_28.setText(_translate("TareaAlgebra", "X2+"))
        self.label_29.setText(_translate("TareaAlgebra", "X2+"))
        self.label_30.setText(_translate("TareaAlgebra", "X2+"))
        self.label_31.setText(_translate("TareaAlgebra", "X1+"))
        self.label_32.setText(_translate("TareaAlgebra", "X1+"))
        self.label_33.setText(_translate("TareaAlgebra", "X1+"))
        self.label_34.setText(_translate("TareaAlgebra", "X1+"))

    def home(self):
        self.matrizEnInterfaz = [[self.FIL1COL1,self.FIL1COL2,self.FIL1COL3,self.FIL1COL4,self.FIL1COL5],
                            [self.FIL2COL1,self.FIL2COL2,self.FIL2COL3,self.FIL2COL4,self.FIL2COL5],
                            [self.FIL3COL1,self.FIL3COL2,self.FIL3COL3,self.FIL3COL4,self.FIL3COL5],
                            [self.FIL4COL1,self.FIL4COL2,self.FIL4COL3,self.FIL4COL4,self.FIL4COL5],
                            [self.FIL5COL1,self.FIL5COL2,self.FIL5COL3,self.FIL5COL4,self.FIL5COL5]]
        self.nuevaMatrizButt.clicked.connect(self.setEnableMatriz)
        self.sResutadosButt.clicked.connect(self.ResolverSistema)

    def ResolverSistema(self):
        self.nuevaMatrizButt.setEnabled(True)
        self.FilasGroupBox.setEnabled(True)
        self.ColumnasGroupBox.setEnabled(True)
        self.resetMatriz(False)
        if not self.generarMatrizReal():
            self.ErrorMessage.setText("Error")
        else:
            bases = self.matrizSYMPY.nullspace()
            numeroBase = 0
            for base in bases:
                cont = 0
                for num in base:
                    self.bases[numeroBase][cont].setText(str(num))
                    cont+=1
                numeroBase += 1
            self.labelSolUnic.setText("La dimensión de la solución es "+str(numeroBase))
            #self.matrizReal = gaussJordan(self.matrizReal)

    def resetMatriz(self, bool):
        for fila in self.matrizEnInterfaz:
            for columna in fila:
                columna.setEnabled(bool)

    def setEnableMatriz(self):
        self.ErrorMessage.setText(" ")
        self.primeraMat = True
        self.resetMatriz(True)
        matriz = self.matrizEnInterfaz
        numCol = 5
        numFil = 5
        if (self.col2.isChecked()):
            numCol = 2
        elif (self.col3.isChecked()):
            numCol = 3
        elif (self.col4.isChecked()):
            numCol = 4
        else:
            pass
        if (self.filas2.isChecked()):
            numFil = 2
        elif (self.filas3.isChecked()):
            numFil = 3
        elif (self.filas4.isChecked()):
            numFil = 4
        else:
            pass
        self.filas = numFil
        self.columnas = numCol
        while (numFil < 5):
            for i in range(0, 5):
                matriz[numFil][i].setEnabled(False)
            numFil += 1
        for i in range(0, 5):
            tmp = numCol
            while (tmp < 5):
                matriz[i][tmp].setEnabled(False)
                tmp += 1
        self.nuevaMatrizButt.setEnabled(False)
        self.FilasGroupBox.setEnabled(False)
        self.ColumnasGroupBox.setEnabled(False)
        self.sResutadosButt.setEnabled(True)
        self.setMatrizActiva()

    def setMatrizActiva(self):
        for i in range(0, self.filas):
            self.matrizActiva.insert(i, [])
            self.matrizReal.insert(i, [])
            for j in range(0, self.columnas):
                self.matrizActiva[i].insert(j, self.matrizEnInterfaz[i][j])

    def generarMatrizReal(self):
        self.matrizReal = []
        for i in range(0, self.filas):
            self.matrizReal.insert(i, [])
        for i in range(0, self.filas):
            for j in range(0, self.columnas):
                tmp = self.matrizActiva[i][j].children()
                num1 = int(tmp[0].text())
                num2 = int(tmp[2].text())
                if num1 == 0:
                    return False
                self.matrizReal[i].insert(j, Fraction(num2, num1))
        for i in self.matrizReal:
            if (len(i) == 0):
                self.matrizReal.remove(i)
        self.matrizSYMPY = Matrix(self.matrizReal)
        return True


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TareaAlgebra = QtWidgets.QMainWindow()
    ui = Ui_TareaAlgebra()
    ui.setupUi(TareaAlgebra)
    TareaAlgebra.show()
    sys.exit(app.exec_())

